import os
import argparse
import json
import torch
import pandas as pd
from comet import download_model, load_from_checkpoint

def parse_args():
    parser = argparse.ArgumentParser(description="WMT Translation Evaluator (COMET)")
    parser.add_argument("--translation_file", type=str, required=True, help="Path to the json translation file generated by benchmark.py")
    parser.add_argument("--comet_model", type=str, default="Unbabel/wmt22-comet-da", help="COMET model to use for evaluation")
    parser.add_argument("--batch_size", type=int, default=8, help="Batch size for COMET model prediction")
    parser.add_argument("--summary_csv", type=str, default="outputs/benchmark_summary.csv", help="Path to benchmark summary CSV file to update")
    return parser.parse_args()

def main():
    args = parse_args()
    
    if not os.path.exists(args.translation_file):
        raise FileNotFoundError(f"[!] Translation file not found: {args.translation_file}")
        
    print(f"=== Starting COMET Evaluation ===")
    print(f"File: {args.translation_file}")
    print(f"COMET Model: {args.comet_model}")
    
    # Extract model and precision from filename
    # E.g. outputs/google_gemma-2b_fp16_translations.json -> model="google/gemma-2b", precision="fp16"
    filename = os.path.basename(args.translation_file)
    src_lang, tgt_lang = "Unknown", "Unknown"
    if filename.endswith("_translations.json"):
        parts = filename[:-len("_translations.json")].split("_")
        # The filename format is {model_alias}_{precision}_{src_lang}_{tgt_lang}_translations.json
        # Language codes like ces_Latn contain one underscore, so they split into two parts: ["ces", "Latn"]
        if len(parts) >= 5:
            tgt_lang = f"{parts[-2]}_{parts[-1]}"
            src_lang = f"{parts[-4]}_{parts[-3]}"
            precision = parts[-5]
            model_alias = "_".join(parts[:-5])
        else:
            precision = parts[-1]
            model_alias = "_".join(parts[:-1])
            
        if "_" in model_alias:
            model = model_alias.replace("_", "/", 1)
        else:
            model = model_alias
    else:
        model = "Unknown"
        precision = "Unknown"
        
    # Load translation results
    with open(args.translation_file, "r", encoding="utf-8") as f:
        translations = json.load(f)
        
    print(f"[*] Loaded {len(translations)} translation sentences.")
    
    # Prepare data for COMET
    data = []
    for item in translations:
        data.append({
            "src": item["source"],
            "mt": item["translation"],
            "ref": item["reference"]
        })
        
    # Download and load COMET model
    print("[*] Downloading/Loading COMET checkpoint...")
    model_path = download_model(args.comet_model)
    
    # Determine devices
    gpus = 1 if torch.cuda.is_available() else 0
    print(f"[*] Loading model from checkpoint on {'GPU (CUDA)' if gpus else 'CPU'}...")
    comet_model = load_from_checkpoint(model_path)
    
    print("[*] Running COMET predictions...")
    predictions = comet_model.predict(data, batch_size=args.batch_size, gpus=gpus)
    
    system_score = predictions.system_score
    scores = predictions.scores
    
    print(f"[*] COMET System Score: {system_score:.4f}")
    
    # Add individual scores back to translation details
    for idx, item in enumerate(translations):
        item["comet_score"] = float(scores[idx])
        
    # Overwrite the translation JSON file with the updated scores
    with open(args.translation_file, "w", encoding="utf-8") as f:
        json.dump(translations, f, ensure_ascii=False, indent=2)
    print(f"[*] Updated translation file with individual COMET scores: {args.translation_file}")
    
    # Update CSV Summary
    if os.path.exists(args.summary_csv):
        print(f"[*] Updating summary CSV: {args.summary_csv}")
        df = pd.read_csv(args.summary_csv)
        
        # Check if the row matches our model and precision
        # E.g. we matches by model name (or alias) and precision
        # Since model name in CSV is the full Hugging Face name, let's look for matching entries
        # Check if the row matches our model, precision, and language pair
        if "src_lang" in df.columns and "tgt_lang" in df.columns:
            mask = (df["precision"] == precision) & \
                   (df["model"].apply(lambda x: x.replace("/", "_") == model_alias or x == model)) & \
                   (df["src_lang"] == src_lang) & \
                   (df["tgt_lang"] == tgt_lang)
        else:
            mask = (df["precision"] == precision) & (df["model"].apply(lambda x: x.replace("/", "_") == model_alias or x == model))
        
        if mask.any():
            df.loc[mask, "comet_score"] = system_score
            print(f"[+] Updated matching row in summary CSV with COMET score: {system_score:.4f}")
        else:
            # Append a new row if not found
            print(f"[!] No matching row found in CSV. Appending new entry...")
            from datetime import datetime
            new_row = {
                "model": [model],
                "precision": [precision],
                "src_lang": [src_lang],
                "tgt_lang": [tgt_lang],
                "load_time_sec": [None],
                "peak_vram_mb": [None],
                "avg_tokens_per_sec": [None],
                "comet_score": [system_score],
                "timestamp": [datetime.now().strftime("%Y-%m-%d %H:%M:%S")]
            }
            df = pd.concat([df, pd.DataFrame(new_row)], ignore_index=True)
            
        df.to_csv(args.summary_csv, index=False)
    else:
        # Create CSV if it doesn't exist
        print(f"[!] Summary CSV does not exist. Creating new one at {args.summary_csv}")
        from datetime import datetime
        summary_data = {
            "model": [model],
            "precision": [precision],
            "src_lang": [src_lang],
            "tgt_lang": [tgt_lang],
            "load_time_sec": [None],
            "peak_vram_mb": [None],
            "avg_tokens_per_sec": [None],
            "comet_score": [system_score],
            "timestamp": [datetime.now().strftime("%Y-%m-%d %H:%M:%S")]
        }
        df = pd.DataFrame(summary_data)
        df.to_csv(args.summary_csv, index=False)
        
    print(f"=== COMET Evaluation Complete ===")

if __name__ == "__main__":
    main()
